
# The services of the project.
#
# Each service listed will be deployed in its own container as part of your
# Platform.sh project.
#
# See https://docs.platform.sh/user_guide/reference/services-yaml.html

db:
    type: postgresql:12
    disk: 1024